### ISSUE TITLE
Add repo to codeclimate

### ISSUE THREAD

**Issue by sivakumar-kailasam** [kesha-shah/ember-fb-app#3]
[Code climate](https://codeclimate.com) is an awesome service that monitors the health of a repo and gives continues stats. Configure this repo on it :smiley:

**Comment by sivakumar-kailasam** [comment]
Here's a sample https://codeclimate.com/github/emberjs/ember.js

**Comment by kesha-shah** [comment]
added this repo to Code-climate

https://codeclimate.com/github/kesha-shah/ember-fb-app

**Comment by sivakumar-kailasam** [comment]
Add the code climate badge to your readme file
