### ISSUE TITLE
Ember materialize

### ISSUE THREAD

**Issue by sivakumar-kailasam** [kesha-shah/ember-fb-app#4]
[Ember materialize](http://mike.works/ember-cli-materialize/) is inspired by Google's material design. This will make the app feel little jazzy and help you focus on the app instead of design. Add this to your app.

**Comment by kesha-shah** [comment]
Added this to my app.

**Comment by sivakumar-kailasam** [comment]
If your commit message says closes/fixes #4(issue no) then these issues will automatically get closed
